# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-29 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demygram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Comment',
        ),
    ]
