# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-31 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demygram', '0002_auto_20201229_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
