# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 08:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demygram', '0005_auto_20210103_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='users',
        ),
        migrations.AddField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demygram.Profile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
