# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demygram', '0006_auto_20210104_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demygram.Profile'),
        ),
    ]
