# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-04 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demygram', '0007_post_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='profile',
        ),
    ]
