# Generated by Django 3.1.5 on 2021-01-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demygram', '0011_auto_20210108_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='count',
        ),
    ]
